/**
 * Created by alphabeta on 16-12-29.
 */

// module
export const GIFT_QUERY_SENDDETAIL_BEGIN = 'GIFT_QUERY_SENDDETAIL_BEGIN'
export const GIFT_QUERY_SENDDETAIL_SUC = 'GIFT_QUERY_SENDDETAIL_SUC'
export const GIFT_QUERY_SENDLIST_BEGIN = 'GIFT_QUERY_SENDLIST_BEGIN'
export const GIFT_QUERY_SENDLIST_SUC = 'GIFT_QUERY_SENDLIST_SUC'
