/**
 * Created by alphabeta on 16-12-29.
 */

// module
export const ADDRESS_QUERY_ADDRESS_BEGIN = 'ADDRESS_QUERY_ADDRESS_BEGIN'
export const ADDRESS_QUERY_ADDRESS_SUC = 'ADDRESS_QUERY_ADDRESS_SUC'
export const ADDRESS_QUERY_ADDRESSS_BEGIN = 'ADDRESS_QUERY_ADDRESSS_BEGIN'
export const ADDRESS_QUERY_ADDRESSS_SUC = 'ADDRESS_QUERY_ADDRESSS_SUC'
export const ADDRESS_SELECT_SUC = 'ADDRESS_SELECT_SUC'
export const ADDRESS_ADD_SUC = 'ADDRESS_ADD_SUC'
export const ADDRESS_UPDATE_SUC = 'ADDRESS_UPDATE_SUC'
export const ADDRESS_DELETE_BEGIN = 'ADDRESS_DELETE_BEGIN'
export const ADDRESS_DELETE_SUC = 'ADDRESS_DELETE_SUC'
