/**
 * Created by alphabeta on 16-12-29.
 */

// module
export const GIFT_QUERY_ASKFORGIVEDETAIL_BEGIN = 'GIFT_QUERY_ASKFORGIVEDETAIL_BEGIN'
export const GIFT_QUERY_ASKFORGIVEDETAIL_SUC = 'GIFT_QUERY_ASKFORGIVEDETAIL_SUC'
export const GIFT_QUERY_GAINLIST_BEGIN = 'GIFT_QUERY_GAINLIST_BEGIN'
export const GIFT_QUERY_GAINLIST_SUC = 'GIFT_QUERY_GAINLIST_SUC'
export const GIFT_QUERY_BASEINFO_BEGIN = 'GIFT_QUERY_BASEINFO_BEGIN'
export const GIFT_QUERY_BASEINFO_SUC = 'GIFT_QUERY_BASEINFO_SUC'
export const GIFT_QUERY_GAININFO_BEGIN = 'GIFT_QUERY_GAININFO_BEGIN'
export const GIFT_QUERY_GAININFO_SUC = 'GIFT_QUERY_GAININFO_SUC'
export const GIFT_ADDRESS_ADD_SUC = 'GIFT_ADDRESS_ADD_SUC'
export const GIFT_DELIVERY_SUC = 'GIFT_DELIVERY_SUC'
export const GIFT_TAKE_BEGIN = 'GIFT_TAKE_BEGIN'
export const GIFT_TAKE_SUC = 'GIFT_TAKE_SUC'
