/**
 * Created by alphabeta on 16-12-29.
 */

// module
export const GIFT_QUERY_GAINDETAIL_BEGIN = 'GIFT_QUERY_GAINDETAIL_BEGIN'
export const GIFT_QUERY_GAINDETAIL_SUC = 'GIFT_QUERY_GAINDETAIL_SUC'
export const GIFT_QUERY_GAINLIST_BEGIN = 'GIFT_QUERY_GAINLIST_BEGIN'
export const GIFT_QUERY_GAINLIST_SUC = 'GIFT_QUERY_GAINLIST_SUC'
export const GIFT_QUERY_GAININFO_BEGIN = 'GIFT_QUERY_GAININFO_BEGIN'
export const GIFT_QUERY_GAININFO_SUC = 'GIFT_QUERY_GAININFO_SUC'
