/**
 * Created by alphabeta on 16-12-29.
 */

// module
export const WANTTO_QUERY_GOODSLIST_BEGIN = 'WANTTO_QUERY_GOODSLIST_BEGIN'
export const WANTTO_QUERY_GOODSLIST_SUC = 'WANTTO_QUERY_GOODSLIST_SUC'
export const WANTTO_BUDGET_SUC = 'WANTTO_BUDGET_SUC'
export const WANTTO_SWITCH_BEGIN = 'WANTTO_SWITCH_BEGIN'
export const WANTTO_SWITCH_SUC = 'WANTTO_SWITCH_SUC'
export const WANTTO_SHARE_SUC = 'WANTTO_SHARE_SUC'
